name: Build Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: docker-compose build
    
    - name: Create build directory
      run: mkdir -p build
    
    - name: Build Linux version
      run: |
        docker-compose run --rm godot-build bash -c "godot --headless --export-release 'Linux/X11' ../build/supertux-kart-clone-linux.x86_64" || echo "Build may require export templates"
    
    - name: Build Windows version  
      run: |
        docker-compose run --rm godot-build bash -c "godot --headless --export-release 'Windows Desktop' ../build/supertux-kart-clone-windows.exe" || echo "Build may require export templates"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: game-builds
        path: build/*
        if-no-files-found: warn
    
    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: build/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}